homeassistant:
  # Name of the location where Home Assistant is running
  name: Masarn Goch
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 195
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url
    
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

scene: !include scenes.yaml

automation: !include automations.yaml

updater:

discovery:

history:

sun:

person:
